version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - echo Build Phase
      - npm run build
      - aws s3 cp dist/ s3://unofficial-seattle-metro-api-site/ --recursive
  post_build:
    commands:
      - echo PostBuild Phase

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist'
