version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.16.3
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - echo Build Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
